language: node_js
env:
  global:
  - secure: ClXsLRNsRkhXxY/X/NeMUBD/seD9bMc92Q4TPTbnmL/0C/qwYZhpeoJ+3ZnUxlwUb9HaDjnTmsUiv/gTSKVbobWsndroP0sw2IpFWHXBkpjIXP7/rHMMiZYlyQ6N3CKs8prYmFw8W3X9x/lCW/ot6WvsfaNTJilm2fGum09ZtJs=
node_js:
- '0.10'
before_install:
- npm uninstall psi browser-sync --save-dev
script:
- node ./node_modules/gulp/bin/gulp build --release
after_success:
- git config --global user.name = "Konstantin Tarkus"
- git config --global user.email = "hello@tarkus.me"
- node ./node_modules/gulp/bin/gulp deploy --production
